apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-service
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: favorites
  template:
    metadata:
      labels:
        app: favorites
    spec:
      containers:
        - name: favorites-container
          image: davashikashi/favorites-microservice:latest 
          ports:
            - containerPort: 3000  # El puerto en el que el microservicio está escuchando
---
apiVersion: v1
kind: Service
metadata:
  name: favorites-service
spec:
  selector:
    app: favorites  # Asegúrate de que esto coincida con el selector de tu deployment
  ports:
    - protocol: TCP
      port: 80        # Puerto accesible dentro del clúster
      targetPort: 3000 # Puerto interno donde la app escucha (en el contenedor)
  type: LoadBalancer  # Servicio accesible únicamente dentro del clúster


